### ISSUE TITLE
Create template and routes for partnership microsites

### ISSUE THREAD

**Issue by jonuy** [shinetext/aurora#97]
These are intended to function as sign-up landing pages for any campaigns we run with outside partners.

- **Routing:** Open to suggestions here. We could do `/partners/*` or `/p/*`? Maybe support both?
- **Stretch Goal:** React. Templates are currently all rendered server-side with EJS. For the sake of consistency across projects, hopefully developer UX and the ability to start sharing components across our different properties, want to look into what it'd take to use React here?

**Comment by cl2205** [comment]
1. **routing:** i'm thinking /partners/:partner and /p/:partner? Otherwise if it's not a known partner param (ie. `http://shinetext.com/partners/dsdfsdfjsdf`), we would return the 404 page?
2. **react:** think i'm able build this in react and ES6 with some plugins and integrate with ejs -- gonna shoot for this. It would be server-rendered with react's`ReactDOMServer.renderToString`
